app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from flask_login import UserMixin
from  . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    '''
    this is a models class registering users
    '''
              
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    password_hash = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
       
    @property
    
    def password(self):
        '''
        password function
        '''
        raise AttributeError('You cannnot read the password attribute')

    
    def set_password(self, password):
        '''
        function for setting password
        '''

        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        '''
      password verification function
        '''
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User { self.username}'

class Blog(db.Model):
   __tablename__='blog'

   '''
   class for for posting a blog
   
   '''

   id = db.Column(db.Integer,primary_key=True)
   title = db.Column(db.String(255))
   blog = db.Column(db.String)
   time = db.Column(db.DateTime,default=datetime.utcnow)
   comments = db.relationship('Comment',backref='blog',lazy='dynamic')
   user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
   



   def save_blog(self):
       db.session.add(self)
       db.session.commit()



class Comment(db.Model):
   __tablename__='comments'

   '''
   class for for posting a comment
   
   '''

   id = db.Column(db.Integer,primary_key=True)
   comment = db.Column(db.String(255))
   blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))
   
    

   def save_comment(self):
       db.session.add(self)
       db.session.commit()

   
   @classmethod
   def get_comments(cls,id):
        comments = Blog.query.filter_by(user_id=id).all()
        return comments   

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField , SubmitField,BooleanField,RadioField,TextAreaField
from wtforms.validators import DataRequired,Required, Length , Email , EqualTo
from ..models import User,Blog


class BlogForm(FlaskForm):
    blog = TextAreaField('Blog',validators=[DataRequired()])

    title = StringField('title',validators=[DataRequired()])

    submit = SubmitField('submit')


class CommentForm(FlaskForm):
    comment = StringField('comment')

    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'



bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')
  
    # setting config
    # from .requests import configure_request
    # configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask_login import login_required
from flask import render_template,redirect,url_for, flash,request,abort
from flask_login import login_user,current_user
from ..models import User,Blog,Comment
from .forms import BlogForm,CommentForm
from .. import db
from .import main

@main.route("/post/",methods=['GET','POST'])
@login_required
def postblog():
    '''
    this is view funtion for posting a blog 
    '''
    postblog=[]
    form=BlogForm()
    if form.validate_on_submit():

        postblog = Blog(blog=form.blog.data,title=form.title.data)

        postblog.save_blog()
        return redirect(url_for('.postedblog'))
    return render_template('post.html',postblog=postblog,form=form)


@main.route("/",methods=['GET','POST'])
def postedblog():
    '''
    this is view funtion for posting a blog 
    '''
    blog_form=BlogForm()
    comment_form=CommentForm()
    if comment_form.validate_on_submit():

        postcomment = Comment(comment=comment_form.comment.data)

        postcomment.save_comment()

    title = blog_form.title.data  
    blog = blog_form.blog.data
    Comments = comment_form.comment.data
    

    postblog= Blog.query.all()
    postcomment=Comment.query.all()

    return render_template('index.html',title=title,comment=postcomment,blog=postblog,blog_form=blog_form,comment_form=comment_form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles.css') }}">

<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">TechBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.postedblog')}}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{{url_for('main.postblog')}}">post</a>
        </li>
      </ul>
    </div>
  </nav>
  <br>
<div class="container">
<div class="row">
<div class="col-md-8">
{% for postblog in blog %}

 <div class="card border-info mb-3" style="max-width: 40rem;">
        <div class="card-body text-info">
          <h5 class="card-title">{{postblog.title}}</h5>
          <p class="card-text">{{postblog.blog}}</p>
          {% for postcomment in comment %}
          <center><small><i><p>{{postcomment.comment}}</p></i></small></center>
          {% endfor %}
          {{wtf.quick_form(comment_form)}}
          </div>
        </div>
      
{% endfor %}
</div>
<div class="col-md-4">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Subscription</h5>
          <p>subscribe and get posted articles on email</p>
          <input type="text" class="form-control">
          <a href="#" class="btn btn-primary">Subscribe</a>
        </div>
      </div>
  </div>
</div>
</div>
{% endblock%}

app/templates/post.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}

<nav class="navbar navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Techblog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('main.postedblog')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">sign in </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{{url_for('main.postblog')}}">post</a>
        </li>
      </ul>
    </div>
  </nav>

<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">

{{wtf.quick_form(form)}}

</div>
<div class="col-md-2"></div>
{% for postblog in postblog %}
{{postblog.title}}
{% endfor %}

{% for postblog in postblog %}
{{postblog.title}}
{% endfor %}

{% for postblog in postblog %}
{{postblog.blog}}
{% endfor %}
</div>
</div>

{% endblock%}